/** Public origin, used for absolute link-preview URLs. Update it when the site moves to a custom domain. */
export const siteUrl = 'https://pring-nt.pages.dev';

export const siteName = 'pring-nt';

/** Link-preview image, generated by `bun run og` (scripts/og.ts). */
export const ogImage = { path: '/og.png', width: 1200, height: 630 };
